version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    image: nodejs
    container_name: finance_back
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - MONGO_HOSTNAME=${MONGO_HOSTNAME}
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - finance-network

  db:
    image: mongo
    container_name: finance_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE={MONGO_DB}
    ports:
      - '27017:27017'
    networks:
      - finance-network

  logs:
    container_name: logs
    image: amir20/dozzle:latest
    ports:
      - '9999:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  finance-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
